### ISSUE TITLE
Hola! tengo una consulta !

### ISSUE THREAD

**Issue by patosaid** [violetr/tesis#1]
hola Viole!, no sabía como contactarte y asi que te escribo por acá. Mira, soy nuevo en esto de github, empecé a aprender R hace un año y medio. No sé como llegué a tu repositorio, pero vi tu presentación de tesis en pdf, esta muy buena! Quisiera saber que usaste para hacerla, Rmarkdown? justo estaba viendo las opciones que tiene Rmarkdown para hacer presentaciones, ahora que tengo que entregar mi tesis...

Espero veas este mensaje! Saludos! :)

**Comment by violetr** [comment]
Hola! qué bueno que te gusto! :) no, la hice en latex con el paquete beamer super personalizado, empecé uno de cero y elegi las letras, colores etc, y le agregué ese contador de paginas que me lo copié de por algun lado (se ve que tenia bastante tiempo :P). Después busco el tex y te lo mando o lo subo aca, pero me acuerdo que modifiqué algunos themes directamente :S asi que probablemente no quede igual. Si no tenés que poner muchas formulas te recomiendo usar RMarkdown, y mas en particular el paquete xaringan con el que podés poner muchas cosas extra como mapas, gif etc!
Saludos

**Comment by patosaid** [comment]
En latex !!! y te quedó espectacular!, debió haber sido mucho trabajo. Sé que si lo intento hacer en latex demoraré mucho tiempo :( ,  asi que iré por Rmarkdown. Voy a revisar xaringan , no lo habia escuchado, tiene buena pinta!
Pensé que nunca verías el mensaje. Muchas gracias por responder :D  Saludos!!!
